{% set name = "farmOS" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 46b1d4a7eb9130df1e752fc91794f7a682561158e0a4f02bba8b059d0fae3556

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pytest-runner
    - pip
  run:
    - python >=3
    - requests-oauthlib ~=1.3.1
    - pydantic ~=1.7.3

test:
  imports:
    - farmOS
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/farmOS/farmOS.py
  license: GPL-3.0-only
  license_file: LICENSE
  summary: A Python library for interacting with farmOS over API.

extra:
  recipe-maintainers:
    - paul121
